version: 2.1

jobs:
  build:
    macos:
      xcode: 11.6.0
    shell: zsh

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd src/xcode && bundle install
      - run:
          name: Build
          command: cd src/xcode && bundle exec fastlane build
  test:
    macos:
      xcode: 11.6.0
    shell: zsh
    steps:
      - run:
          name: Tests
          command: cd src/xcode
      - run:
          name: Install and run sonar-scanner
          command: |
            SCANNER=sonar-scanner-cli-4.3.0.2102-macosx
            SCANNERDIR=~/sonar/sonar-scanner-4.3.0.2102-macosx
            if [[ ! -x "$SCANNERDIR/bin/sonar-scanner" ]]; then
              curl -Ol https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SCANNER.zip
              unzip -qq -o $SCANNER.zip -d ~/sonar/
            fi
            chmod +x $SCANNERDIR/bin/sonar-scanner
            chmod +x $SCANNERDIR/jre/bin/java
            $SCANNERDIR/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN
          environment:
            SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io"}'
      - save_cache:
          key: sonar-cloud-v2
          paths:
            - ~/sonar/

  grab-screenshots:
    macos:
      xcode: 11.6.0
    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Snapshots
          command: cd src/xcode && bundle exec fastlane snapshot
      - store_artifacts:
          path: src/xcode/screenshots
  testflight-release:
    macos:
      xcode: 11.6.0
    shell: zsh
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd src/xcode && bundle install
      - run: ./scripts/switch_to_dev_env.sh
      - run:
          name: fastlane
          command: cd src/xcode && bundle exec fastlane betaRelease --env TestFlight

workflows:
    test-and-scan:
      jobs:
        - test
    build:
      jobs:
        - build
        - grab-screenshots:
            filters:
              branches:
                only:
                  - master
    betaRelease:
      jobs:
        - testflight-release:
            filters:
              branches:
                only:
                  - /rc\/.*/
